name: 'Run Swap'
on:
  workflow_dispatch:
  pull_request:
    types: [opened, closed]
    branches:
      - appsettings
  
env:
  config_dir: .github/workflows/config

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all

  get-matrix:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.get-matrix.outputs.deployment-matrix }}
    steps:
    - uses: actions/checkout@v3
    - name: Export deployment matrix
      id: get-matrix
      run: |
        node ./index.js test-get-deploy-slots.json
      working-directory: ${{ env.config_dir }}

  get-slot-settings:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: [ get-matrix ]
    steps:
      - uses: actions/checkout@v2
      # SP: github action az webapp swap
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.azure_credentials }}
      - uses: ./
        with:
          mode: get-deploy-slots
          config: ${{ needs.get-matrix.outputs.result }}
          token: ${{ secrets.PAT }}
          repo: mildronize/actions-az-webapp-swap
          
  set-slot-settings:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    name: ${{ format('‚öôÔ∏è Set Slot | {0} - {1}', matrix.name, matrix.slot) }}
    needs: [ get-matrix ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.get-matrix.outputs.result) }}
    steps:
      - uses: actions/checkout@v2
      # SP: github action az webapp swap
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.azure_credentials }}
      
      - name: set-slot-settings
        uses:  ./
        with: 
          mode: set-deploy-slots
          swap-config: ${{ toJson(matrix) }}

  swap-slot:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    name: ${{ format('üöÄ Swap Slot | {0} - {1}', matrix.name, matrix.slot) }}
    needs: [ get-matrix ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.get-matrix.outputs.result) }}
    steps:
      - uses: actions/checkout@v2
      # SP: github action az webapp swap
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.azure_credentials }}
      
      - name: set-slot-settings
        uses:  ./
        with: 
          mode: swap-slots
          swap-config: ${{ toJson(matrix) }}
